### ISSUE TITLE
Erorr! For Ngrok

### ISSUE THREAD

**Issue by Bintangp02** [CI-Devs/Windows-RDP-ACTIONS#7]
Run Set-LocalUser -Name "runneradmin" *** -AsPlainText "" -Force)
  Set-LocalUser -Name "runneradmin" *** -AsPlainText "" -Force)
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
ConvertTo-SecureString: D:\a\_temp\36ba2dfb-1bf0-4e54-b265-b8f6bcde2586.ps1:2
Line |
   2 |  … unneradmin" *** -AsPlainText "" -Force)
     |                                                               ~~
     | Cannot bind argument to parameter 'String' because it is an empty string.

Error: Process completed with exit code 1.

**Comment by dikeckaan** [comment]
Set password secret :) read in readme file
